### ISSUE TITLE
LDC latest fails to install

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#1730]
```
2025-08-04 18:26:57,702 lib.installation_context INFO     Staging with bash -c 'mkdir ldc-latest-ci
cd ldc-latest-ci
chmod +x ../install.sh
# Download and unpack into current directory
ACTIVATE_PATH=$(../install.sh install ldc-latest-ci -a -p $(pwd))
# Rename the downloaded package directory to a constant name
mv $(dirname $ACTIVATE_PATH) ldc
# Make directory readable for other users too
chmod +rx ldc'
curl: (7) Failed to connect to thecybershadow.net port 443 after 323 ms: Connection refused
curl: (7) Failed to connect to thecybershadow.net port 443 after 97 ms: Connection refused
curl: (7) Failed to connect to thecybershadow.net port 443 after 97 ms: Connection refused
curl: (7) Failed to connect to thecybershadow.net port 443 after 98 ms: Connection refused
curl: (7) Failed to connect to thecybershadow.net port 443 after 97 ms: Connection refused
Failed to download 'https://thecybershadow.net/d/github-ldc'
dirname: missing operand
Try 'dirname --help' for more information.
mv: missing destination file operand after 'ldc'
Try 'mv --help' for more information.
chmod: cannot access 'ldc': No such file or directory
2025-08-04 18:27:13,583 lib.ce_install  INFO     compilers/d/nightly/ldc ldc-latest-ci failed to install: Command '['bash', '-c', 'mkdir ldc-latest-ci\ncd ldc-latest-ci\nchmod +x ../install.sh\n# Download and unpack into current directory\nACTIVATE_PATH=$(../install.sh install ldc-latest-ci -a -p $(pwd))\n# Rename the downloaded package directory to a constant name\nmv $(dirname $ACTIVATE_PATH) ldc\n# Make directory readable for other users too\nchmod +rx ldc']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 470, in install
    installable.install()
  File "/home/ubuntu/infra/bin/lib/installable/script.py", line 45, in install
    self.stage(staging)
  File "/home/ubuntu/infra/bin/lib/installable/script.py", line 31, in stage
    self.install_context.stage_command(staging, ["bash", "-c", self.script])
  File "/home/ubuntu/infra/bin/lib/installation_context.py", line 186, in stage_command
    subprocess.check_call(command, cwd=str(cwd or staging.path), env=env)
  File "/home/ubuntu/.local/share/uv/python/cpython-3.12.10-linux-x86_64-gnu/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-c', 'mkdir ldc-latest-ci\ncd ldc-latest-ci\nchmod +x ../install.sh\n# Download and unpack into current directory\nACTIVATE_PATH=$(../install.sh install ldc-latest-ci -a -p $(pwd))\n# Rename the downloaded package directory to a constant name\nmv $(dirname $ACTIVATE_PATH) ldc\n# Make directory readable for other users too\nchmod +rx ldc']' returned non-zero exit status 1.

0 packages installed OK, 0 skipped, and 1 failed installation
Failed:
  compilers/d/nightly/ldc ldc-latest-ci
```

the URL resolves ok locally so I wonder if they're blocking AWS?

**Comment by mattgodbolt** [comment]
CC @JohanEngelen any ideas?

**Comment by CyberShadow** [comment]
Hi, can you get the IP that this request is coming from, please?

**Comment by CyberShadow** [comment]
Thanks, should work now.

(Context: my server was hit by a DDoS last week, which forced me to block a lot of IP ranges which were sending the requests. Some AWS ranges must have been among them. I'm not sure but perhaps things are generally more likely to work if requests are sent from a fixed IP belonging to a private network, or from an IP belonging to an operator who responds swiftly to abuse reports.)

**Comment by mattgodbolt** [comment]
Thanks. Is there another place we can hit instead, behind some cache or other, so that we're not blocked again? I'm sorry to hear about the DDoS attack! :(

**Comment by mattgodbolt** [comment]
Failed:
  compilers/d/nightly/dmd dmd2-nightly

Still happening unfortunately. I guess our IP changed?

**Comment by mattgodbolt** [comment]
My mistake; looks like something got renamed:
```
2025-08-25T06:51:54.7598116Z chmod +rx dmd2'
2025-08-25T06:53:28.5028891Z 2025-08-25 06:53:28,502 lib.installation_context INFO     Moving from staging (/opt/compiler-explorer/staging/bacabcfb-63af-48e5-93c7-37ccc6ec8dbc/dmd2-nightly) to final destination (/opt/compiler-explorer/dmd2-nightly)
2025-08-25T06:53:58.8687394Z 2025-08-25 06:53:58,868 lib.ce_install  INFO     compilers/d/nightly/dmd dmd2-nightly failed to install: [Errno 2] No such file or directory: '/opt/compiler-explorer/staging/bacabcfb-63af-48e5-93c7-37ccc6ec8dbc/dmd2-nightly/dmd-master'
2025-08-25T06:53:58.8688254Z Traceback (most recent call last):
2025-08-25T06:53:58.8688600Z   File "/home/ubuntu/infra/bin/lib/ce_install.py", line 690, in install
2025-08-25T06:53:58.8688923Z     installable.install()
2025-08-25T06:53:58.8689493Z   File "/home/ubuntu/infra/bin/lib/installable/script.py", line 46, in install
2025-08-25T06:53:58.8689962Z     self.install_context.move_from_staging(staging, self.name, self.install_path)
2025-08-25T06:53:58.8690685Z   File "/home/ubuntu/infra/bin/lib/installation_context.py", line 336, in move_from_staging
2025-08-25T06:53:58.8691315Z     self._fix_permissions(source_path)
2025-08-25T06:53:58.8692127Z   File "/home/ubuntu/infra/bin/lib/installation_context.py", line 278, in _fix_permissions
2025-08-25T06:53:58.8692631Z     self._fix_single_permission(file_path)
2025-08-25T06:53:58.8693028Z   File "/home/ubuntu/infra/bin/lib/installation_context.py", line 282, in _fix_single_permission
2025-08-25T06:53:58.8693416Z     current_mode = file_path.stat().st_mode
2025-08-25T06:53:58.8693643Z                    ^^^^^^^^^^^^^^^^
2025-08-25T06:53:58.8694179Z FileNotFoundError: [Errno 2] No such file or directory: '/opt/compiler-explorer/staging/bacabcfb-63af-48e5-93c7-37ccc6ec8dbc/dmd2-nightly/dmd-master'
2025-08-25T06:53:58.8694654Z
```

**Comment by mattgodbolt** [comment]
I ran out of brain power. The installer seems to leave a broken symlink:
```
bollo:/t/moo $ ls -l dmd2/
total 92
-rw-rw-r-- 1 matthew matthew 49658 Aug 25 21:43 d-keyring.gpg
lrwxrwxrwx 1 matthew matthew    25 Aug 25 21:44 dmd-master -> /tmp/moo/dmd2/dmd-nightly
-rwxrwxr-x 1 matthew matthew 38449 Aug 25 21:44 install.sh*
bollo:/t/moo $ ls dmd2/dmd-master 
dmd2/dmd-master@
```

And that's confusing our code. I should fix our code honestly...

**Comment by mattgodbolt** [comment]
hopefully fixed now
